### ISSUE TITLE
Pre-built docker image?

### ISSUE THREAD

**Issue by sobolevn** [sslab-gatech/Rudra#12]
I would love to test this out on my project, but it looks like that there's not pre-built docker image.

You can host one on DockerHub or GitHub Container Registry.
It would be really easier to try this out this way! 👍

**Comment by ammaraskar** [comment]
I've added a github action that should auto build and push docker images built from the repo, you can use:

`docker pull ghcr.io/sslab-gatech/rudra:master && docker tag ghcr.io/sslab-gatech/rudra:master rudra:latest`

before running `docker-cargo-rudra` to pull them down. @Qwaz, shall we add this as an alternative way to run into the README?

**Comment by Qwaz** [comment]
Sure. let me take care of that this evening. Can you also add an image based on #10? We can't accept this PR yet, but we can still publish a docker image based on that.

**Comment by ammaraskar** [comment]
Pushed #10 as `ghcr.io/sslab-gatech/rudra:2021-08-20`: https://github.com/sslab-gatech/Rudra/pkgs/container/rudra/versions?filters%5Bversion_type%5D=tagged

**Comment by Qwaz** [comment]
Updated README with the instruction of how to use Rudra with prebuilt GHCR docker image.
