### ISSUE TITLE
Failed to run 'cargo rudra' for crates

### ISSUE THREAD

**Issue by VaynNecol** [sslab-gatech/Rudra#16]
When I execute `cargo rudra` for other crates, there is an error:

```
dyld: Library not loaded: @rpath/librustc_driver-0fd0d43d50587954.dylib
Referenced from: /Users/vaynnecol/.cargo/bin/cargo-rudra
Reason: image not found
[1] 91286 abort cargo rudra
```

and this error does not apper when i running Rudra for itself.

**Comment by Qwaz** [comment]
You might need to add Rust toolchain library path to `LD_LIBRARY_PATH`.

https://github.com/sslab-gatech/Rudra/blob/5dd2fde48ede245fa522010731f5687a135c0131/Dockerfile#L11-L12

**Comment by Qwaz** [comment]
Could you confirm if it solved your issue?
