### ISSUE TITLE
Rudra can't work well because the toolchain used is quite old.

### ISSUE THREAD

**Issue by SocialistDalao** [sslab-gatech/Rudra#24]
When I use nightly-2021-08-20, it works OK. But nowadays, rust projects support many new features. If I use the same toolchain to compile them, errors like `feature "edition2021" is required` will appear. After I use new version of toolchain. Rudra failed in the compilation because `miri` was recently split into several crates, which makes `rustc_mir` unable to reach. The Rudra requires that the version of toolchains used to build Rudra and target projects must be same. What should I do?

Moreover, I'm very curious about how you analyze 43k packages mentioned in your paper. Is there a project or any scripts?

My Email: loancold@foxmail.com

**Comment by Qwaz** [comment]
Please check [Rudra-Artifacts](https://github.com/sslab-gatech/Rudra-Artifacts) repository for the evaluation detail. Regarding the compiler version issue, please check #19 for a temporary workaround. I will definitely add support for the newer compiler version in the future, but I can't provide concrete ETA at this point of time.

Closing in favor of #19. Feel free to follow up if you have any additional questions :)

**Comment by SocialistDalao** [comment]
Thx a lot. Hope to see it happen soon. XD
