### ISSUE TITLE
Update to latest rust version

### ISSUE THREAD

**Issue by Bergmann89** [sslab-gatech/Rudra#53]
Hey there,

are there any plans to update rudra to the latest rust compiler? Would like to use this on my project :)

Greetings, Bergmann89.

**Comment by 8573** [comment]
I think this is a duplicate of #51.

**Comment by eslerm** [comment]
Most related discussion is in https://github.com/sslab-gatech/Rudra/issues/19

**Comment by Qwaz** [comment]
Closing as duplicate
